# Importing Data

Importing Data dibutuhkan untuk mengambil library-library yang dibutuhkan dan memasukkannya ke dalam lingkungan analisis yang digunakan, tanpa library-library ini proses analisis data bisa terhambat karena library ini dibutuhkan untuk menjalankan proses analisis lebih lanjut.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Exploratory Data Analysis (EDA)

Exploratory Data Analysis (EDA) dalam bahasa Indonesia sebagai Analisis Data Eksploratif ini salah satu langkah yang dibutuhkan dalam menganalisis data. Langkah ini melibatkan pemeriksaan dataset yang bertujuan untuk memahami data yang sedang di analisis , mengidentifikasi kesalahan dalam data, menemukan pola dan hubungan antara variabel, dan mempersiapkan data untuk analisis lanjutan.

In [2]:
dt = pd.read_csv("dataset/diabetes_dataset.csv")
dt

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [3]:
dt.describe()

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes
count,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,41.885856,0.07485,0.039420,27.320767,5.527507,138.058060,0.085000
std,22.516840,0.26315,0.194593,6.636783,1.070672,40.708136,0.278883
min,0.080000,0.00000,0.000000,10.010000,3.500000,80.000000,0.000000
25%,24.000000,0.00000,0.000000,23.630000,4.800000,100.000000,0.000000
50%,43.000000,0.00000,0.000000,27.320000,5.800000,140.000000,0.000000
75%,60.000000,0.00000,0.000000,29.580000,6.200000,159.000000,0.000000
max,80.000000,1.00000,1.000000,95.690000,9.000000,300.000000,1.000000

In [4]:
dt.dtypes

gender                  object
age                    float64
hypertension             int64
heart_disease            int64
smoking_history         object
bmi                    float64
HbA1c_level            float64
blood_glucose_level      int64
diabetes                 int64
dtype: object

# Data Information

In [5]:
dt.heart_disease.unique()

array([1, 0], dtype=int64)

In [6]:
dt.hypertension.unique()

array([0, 1], dtype=int64)

In [7]:
dt.diabetes.unique()

array([0, 1], dtype=int64)

In [8]:
dt.smoking_history.unique()

array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
      dtype=object)

In [9]:
dt.gender.unique()

array(['Female', 'Male', 'Other'], dtype=object)

In [10]:
dt.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

# One Hot Encode

In [11]:
encode = pd.get_dummies(dt, prefix=None)
encode

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes,gender_Female,gender_Male,gender_Other,smoking_history_No Info,smoking_history_current,smoking_history_ever,smoking_history_former,smoking_history_never,smoking_history_not current
0,80.0,0,1,25.19,6.6,140,0,1,0,0,0,0,0,0,1,0
1,54.0,0,0,27.32,6.6,80,0,1,0,0,1,0,0,0,0,0
2,28.0,0,0,27.32,5.7,158,0,0,1,0,0,0,0,0,1,0
3,36.0,0,0,23.45,5.0,155,0,1,0,0,0,1,0,0,0,0
4,76.0,1,1,20.14,4.8,155,0,0,1,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,80.0,0,0,27.32,6.2,90,0,1,0,0,1,0,0,0,0,0
99996,2.0,0,0,17.37,6.5,100,0,1,0,0,1,0,0,0,0,0
99997,66.0,0,0,27.83,5.7,155,0,0,1,0,0,0,0,1,0,0
99998,24.0,0,0,35.42,4.0,100,0,1,0,0,0,0,0,0,1,0
99999,57.0,0,0,22.43,6.6,90,0,1,0,0,0,1,0,0,0,0

# Normalize Data

Mengapa kita perlu melakukan Data Normalisasi? Karena ketika melakukan pemodelan data, diantaranya dengan SVM, Regresi Linier, dan sejenisnya, perbedaan rentan nilai dalam tiap-tiap nilai sel pada data akan mempengaruhi kinerja algoritma yang akan dilakukan, sehingga menghilangkan perbedaan skala dan mengurangi efek outlier perlu dilakukan

In [12]:
from sklearn import preprocessing

scaler = preprocessing.MinMaxScaler()
d = scaler.fit_transform(encode)
data_normalisasi = pd.DataFrame(d, columns=encode.columns)
data_normalisasi

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes,gender_Female,gender_Male,gender_Other,smoking_history_No Info,smoking_history_current,smoking_history_ever,smoking_history_former,smoking_history_never,smoking_history_not current
0,1.000000,0.0,1.0,0.177171,0.563636,0.272727,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.674675,0.0,0.0,0.202031,0.563636,0.000000,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.349349,0.0,0.0,0.202031,0.400000,0.354545,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.449449,0.0,0.0,0.156863,0.272727,0.340909,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.949950,1.0,1.0,0.118231,0.236364,0.340909,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1.000000,0.0,0.0,0.202031,0.490909,0.045455,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
99996,0.024024,0.0,0.0,0.085901,0.545455,0.090909,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
99997,0.824825,0.0,0.0,0.207983,0.400000,0.340909,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
99998,0.299299,0.0,0.0,0.296569,0.090909,0.090909,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
99999,0.712212,0.0,0.0,0.144958,0.563636,0.045455,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

# Split Test

In [13]:
from sklearn.model_selection import train_test_split
X = data_normalisasi.drop(['diabetes', 'hypertension', 'heart_disease'], axis=1)
y = data_normalisasi['diabetes']

# Test = 20% dan Train = 80%
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [14]:
X_train

,age,bmi,HbA1c_level,blood_glucose_level,gender_Female,gender_Male,gender_Other,smoking_history_No Info,smoking_history_current,smoking_history_ever,smoking_history_former,smoking_history_never,smoking_history_not current
44696,0.186687,0.130602,0.236364,0.022727,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
98180,0.374374,0.202031,0.090909,0.227273,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
39211,0.562062,0.224556,0.418182,0.000000,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
63452,0.774775,0.372666,0.418182,0.272727,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
27777,0.074074,0.089286,0.181818,0.295455,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
50384,0.336837,0.202031,0.454545,0.209091,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
56182,0.774775,0.213936,0.400000,0.363636,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
68769,0.261762,0.202031,0.272727,0.545455,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
99032,0.874875,0.317110,0.000000,0.227273,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
67369,0.361862,0.202031,0.090909,0.227273,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [15]:
X_test

,age,bmi,HbA1c_level,blood_glucose_level,gender_Female,gender_Male,gender_Other,smoking_history_No Info,smoking_history_current,smoking_history_ever,smoking_history_former,smoking_history_never,smoking_history_not current
43007,0.549550,0.115896,0.000000,0.090909,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
25295,0.474474,0.254902,0.400000,0.636364,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
15638,0.537037,0.202031,0.545455,0.272727,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
84183,0.374374,0.381419,0.400000,0.000000,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
82848,0.599600,0.204482,0.563636,0.272727,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99164,0.899900,0.202031,0.400000,0.363636,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
51089,0.799800,0.130135,0.490909,0.295455,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
95957,0.136637,0.202031,0.472727,0.000000,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
19945,0.424424,0.202031,0.454545,0.545455,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
19190,0.762262,0.145075,0.236364,0.363636,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [16]:
y_train

44696    0.0
98180    0.0
39211    0.0
63452    1.0
27777    0.0
        ...
50384    0.0
56182    0.0
68769    0.0
99032    0.0
67369    0.0
Name: diabetes, Length: 80000, dtype: float64

# Training Model - SVM

In [17]:
from sklearn import svm
model_svm = svm.SVC()

In [18]:
model = model_svm.fit(X_train, y_train)

# Evaluasi Model - SVM

In [19]:
accuracy_test_svm = model_svm.score(X_test,y_test)

In [20]:
accuracy_train_svm = model_svm.score(X_train,y_train)

In [21]:
print(f"Akurasi Model (Train) : {np.round(accuracy_train_svm * 100,2)} %")
print(f"Akurasi Model (Test)  : {np.round(accuracy_test_svm * 100,2)} %")

Akurasi Model (Train) : 96.14 %
Akurasi Model (Test)  : 96.12 %

# Prediction - SVM

In [22]:
df_test = pd.DataFrame(data={
    "age" : [51, 28],
    "gender"  : ["Female", "Male"],
    "smoking_history" : ["current", "never"],
    "bmi": [23.45, 21.67],
    "HbA1c_level": [4.8, 5.4],
    "blood_glucose_level": [158, 142],
})

df_test

   age  gender smoking_history    bmi  HbA1c_level  blood_glucose_level
0   51  Female         current  23.45          4.8                  158
1   28    Male           never  21.67          5.4                  142

In [23]:
encode_test = pd.get_dummies(df_test, prefix=None)
encode_test

encode_test

,age,bmi,HbA1c_level,blood_glucose_level,gender_Female,gender_Male,smoking_history_current,smoking_history_never
0,51,23.45,4.8,158,1,0,1,0
1,28,21.67,5.4,142,0,1,0,1

In [31]:
a=[]
for i in range(len(encode_test)):
    if encode_test["gender_Female"][i]==1 or encode_test["gender_Male"][i]==1:
        a.append(0)
    elif encode_test["gender_Female"][i] != 1 and encode_test["gender_Male"][i] != 1:
        a.append(1)
    else:
        continue
encode_test["gender_Other"]= a
encode_test

,age,bmi,HbA1c_level,blood_glucose_level,gender_Female,gender_Male,smoking_history_current,smoking_history_never,gender_Other
0,51,23.45,4.8,158,1,0,1,0,0
1,28,21.67,5.4,142,0,1,0,1,0

In [32]:
pred_test = model.predict(encode_test)

ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- smoking_history_No Info
- smoking_history_ever
- smoking_history_former
- smoking_history_not current

# K-Neiress Neighbors

In [34]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)

In [35]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

# Evaluasi Model - K-Neiress Neighbors

In [37]:
accuracy_test_knn = knn.score(X_test, y_test)

In [38]:
accuracy_train_knn = knn.score(X_train, y_train)

In [39]:
print(f"Akurasi Model (Train) : {np.round(accuracy_train_knn * 100,2)} %")
print(f"Akurasi Model (Test)  : {np.round(accuracy_test_knn * 100,2)} %")

Akurasi Model (Train) : 97.5 %
Akurasi Model (Test)  : 96.3 %

In [40]:
knn_palette = sns.color_palette(['#000C1F', '#29757A', '#FF5050'])
knn_palette

[(0.0, 0.047058823529411764, 0.12156862745098039),
 (0.1607843137254902, 0.4588235294117647, 0.47843137254901963),
 (1.0, 0.3137254901960784, 0.3137254901960784)]

In [43]:
sns.scatterplot(x = X_train[:, 0], y = X_train[:, 1],
                 hue = y_train,
                 palette = knn_palette, 
                 markers= [',', '^', 'P'],
                 style = y_train,
                 s = 100,
                 legend = True)

InvalidIndexError: (slice(None, None, None), 0)